// ⚠️ THIS FILE IS AUTO-GENERATED BY GITHUB ACTIONS
// Do not commit this file with real credentials
// Real values are injected from GitHub Secrets during CI/CD

export const environment = {
  production: true,
  firebase: {
    apiKey: 'PLACEHOLDER_WILL_BE_REPLACED_BY_CI',
    authDomain: 'PLACEHOLDER_WILL_BE_REPLACED_BY_CI',
    projectId: 'PLACEHOLDER_WILL_BE_REPLACED_BY_CI',
    storageBucket: 'PLACEHOLDER_WILL_BE_REPLACED_BY_CI',
    messagingSenderId: 'PLACEHOLDER_WILL_BE_REPLACED_BY_CI',
    appId: 'PLACEHOLDER_WILL_BE_REPLACED_BY_CI'
  }
};
